### ISSUE TITLE
Need help ! 

### ISSUE THREAD

**Issue by biraguha** [Integreight/1Sheeld-Android-SDK#2]
Hi,

I would like to simulate the orientation sensor shield but i don't know how to do that.
Do you have a solution for me ?

**Comment by isso** [comment]
This is [the main logic of the orientation shield](https://github.com/Integreight/1Sheeld-Android-App/blob/master/oneSheeld/src/main/java/com/integreight/onesheeld/shields/controller/OrientationShield.java) in the Android app's repo. It is very simple, you can figure it out yourself. :)
