### ISSUE TITLE
React Native lib?

### ISSUE THREAD

**Issue by Norfeldt** [Integreight/1Sheeld-Android-SDK#3]
This is probably too much to ask and understand if you don't want to. 

It would be awesome if this SDK gets ported to an react native lib (wouldn't mind if it's android only) - would make it extremely fast to develop the UI and try out some 1Sheeld functionality.

**Comment by isso** [comment]
It is a great idea indeed, and I think it will at least help prototype apps faster, but unfortunately, we don't have enough time or resources to do it.

We tried to make the SDK as readable and as documented as possible, so it can be forked/built upon easily. So we encourage you - if you have the time - to do it yourself.

**Comment by Norfeldt** [comment]
I understand, but it was worth asking.

Unfortunately I don't know how to port native code to react native.
